CREATE TABLE IF NOT EXISTS banks (
    id BIGSERIAL PRIMARY KEY,
    code VARCHAR(32) UNIQUE NOT NULL,
    name VARCHAR(128) NOT NULL,
    address VARCHAR(256)
);

CREATE TABLE IF NOT EXISTS clients (
    id BIGSERIAL PRIMARY KEY,
    bank_id BIGINT NOT NULL REFERENCES banks(id) ON DELETE CASCADE,
    name VARCHAR(128) NOT NULL,
    address VARCHAR(256),
    birth_day DATE,
    premium BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS accounts (
    id BIGSERIAL PRIMARY KEY,
    client_id BIGINT NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
    iban VARCHAR(64) UNIQUE NOT NULL,
    currency VARCHAR(8) NOT NULL,
    balance DOUBLE PRECISION NOT NULL
);

CREATE TABLE IF NOT EXISTS operations (
    id BIGSERIAL PRIMARY KEY,
    type VARCHAR(16) NOT NULL,
    source_iban VARCHAR(64),
    destination_iban VARCHAR(64),
    amount DOUBLE PRECISION NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(16) NOT NULL
);
